# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2229cf757f15fac252a6ca1b485f89e68358b7b4616394fc45f37179e4e8f58d22fee34fa1766459b21f7c39624a85a3b98f4e671f29fe01fd9804f69b8219

test:
  secret_key_base: 2bc4fab99183a8b5124628e2f9221d467f416bf954e7c7d42547a17a6146854f899c558487dbdda359d80d87047df64c45c3c6e7e198ab69842814962a28adf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
