default: &default
  adapter: postgresql
  template: template0
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: zero_test
  username: xpuser_test
  password: zero_password_test

development:
  <<: *default
  database: zero_development
  username: xpuser
  password: zero_password_development

production:
  <<: *default
  database: zero_production
  username: zero_username_production
  password: zero_password_production
