# Tutti i metodi di FileUtils sono automaticamente disponibile nel Rakefile.

desc 'Default task; it is invoked with no parameters'
task :default do
	puts 'Default!'
end

desc 'Remove the Unix backup files (eg: my-file.txt~)'
task :delete_unix_backups do
	delete('*~')
end

desc 'Remove the Windows backup files (eg: my-file.bak)'
task :delete_windows_backups do
	delete('*.bak')
end
	
desc 'Remove Unix and Windows backup files'
task :delete_backups => [:delete_unix_backups, :delete_windows_backups] do
	puts 'All backup files deleted!'
end	

def delete(pattern)
	files = Dir[pattern]
	rm(files, verbose: true) unless files.empty?
end